export const LOGIN_USER = 'LOGIN USER [LOGIN_USER]'
export const LOGIN_USER_SUCCESS = 'LOGIN USER SUCCESS [LOGIN_USER_SUCCESS]'
export const LOGIN_USER_FAILED = 'LOGIN USER FAILED [LOGIN_USER_FAILED]'