export const LOGIN_USER = 'LOGIN USER [LOGIN_USER]'
export const LOGIN_USER_SUCCESS = 'LOGIN USER SUCCESS [LOGIN_USER_SUCCESS]'
export const LOGIN_USER_FAILED = 'LOGIN USER FAILED [LOGIN_USER_FAILED]'

export const VERIFY_USER = 'VERIFY USER [VERIFY_USER]'
export const VERIFY_USER_SUCCESS = 'VERIFY USER SUCCESS [VERIFY_USER_SUCCESS]'
export const VERIFY_USER_FAILED = 'VERIFY USER FAILED [VERIFY_USER_FAILED]'