export const ADD_PROFILE = 'ADD PROFILE [ADD_PROFILE]'
export const ADD_PROFILE_SUCCESS = 'ADD PROFILE SUCCESS [ADD_PROFILE_SUCCESS]'
export const ADD_PROFILE_FAILED = 'ADD PROFILE FAILED [ADD_PROFILE_FAILED]'

export const GET_PROFILE = 'GET PROFILE [GET_PROFILE]'
export const GET_PROFILE_SUCCESS = 'GET PROFILE SUCCESS [GET_PROFILE_SUCCESS]'
export const GET_PROFILE_FAILED = 'GET PROFILE FAILED [GET_PROFILE_FAILED]'

export const UPDATE_PROFILE = 'UPDATE PROFILE [UPDATE_PROFILE]'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE PROFILE SUCCESS [UPDATE_PROFILE_SUCCESS]'
export const UPDATE_PROFILE_FAILED = 'UPDATE PROFILE FAILED [UPDATE_PROFILE_FAILED]'

export const UPLOAD_FILE= 'UPLOAD FILE [UPLOAD_FILE]';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD FILE SUCCESS [UPLOAD_FILE_SUCCESS]';
export const UPLOAD_FILE_FAILED = 'UPLOAD FILE FAILED [UPLOAD_FILE_FAILED]';

export const RESET_FORM = 'RESET FORM [RESET_FORM]'
export const SHOW_CODE = 'SHOW CODE [SHOW_CODE]'