export const SEARCH_CALLED = 'SEARCH CALLED [SEARCH_CALLED]'
export const SEARCH_CALLED_SUCCESS = 'SEARCH CALLED SUCCESS [SEARCH_CALLED_SUCCESS]'
export const SEARCH_CALLED_FAILED = 'SEARCH CALLED FAILED [SEARCH_CALLED_FAILED]'

export const GET_USERS = 'GET USERS [GET_USERS]'
export const GET_USERS_SUCCESS = 'GET USERS SUCCESS [GET_USERS_SUCCESS]'
export const GET_USERS_FAILED = 'GET USERS FAILED [GET_USERS_FAILED]'

export const GET_PARAMS = 'GET PARAMS [GET_PARAMS]'
export const GET_PARAMS_SUCCESS = 'GET PARAMS SUCCESS [GET_PARAMS_SUCCESS]'
export const GET_PARAMS_FAILED = 'GET PARAMS FAILED [GET_PARAMS_FAILED]'


export const SEARCH_DATA = 'SEARCH DATA [SEARCH_DATA]'
export const GET_LOCATION = 'GET LOCATION [GET_LOCATION]'