export const SEARCH_CALLED = 'SEARCH CALLED [SEARCH_CALLED]'
export const SEARCH_CALLED_SUCCESS = 'SEARCH CALLED SUCCESS [SEARCH_CALLED_SUCCESS]'
export const SEARCH_CALLED_FAILED = 'SEARCH CALLED FAILED [SEARCH_CALLED_FAILED]'