export const SIGNUP_USER = 'SIGNUP USER [SIGNUP_USER]'
export const SIGNUP_USER_SUCCESS = 'SIGNUP USER SUCCESS [SIGNUP_USER_SUCCESS]'
export const SIGNUP_USER_FAILED = 'SIGNUP USER FAILED [SIGNUP_USER_FAILED]'