export const SIGNUP_USER = 'SIGNUP USER [SIGNUP_USER]'
export const SIGNUP_USER_SUCCESS = 'SIGNUP USER SUCCESS [SIGNUP_USER_SUCCESS]'
export const SIGNUP_USER_FAILED = 'SIGNUP USER FAILED [SIGNUP_USER_FAILED]'

export const RESET_PASSWORD = 'RESET PASSWORD [RESET_PASSWORD]'
export const RESET_PASSWORD_SUCCESS = 'RESET PASSWORD SUCCESS [RESET_PASSWORD_SUCCESS]'
export const RESET_PASSWORD_FAILED = 'RESET PASSWORD FAILED [RESET_PASSWORD_FAILED]'